### ISSUE TITLE
Extract cli, server and middleware into broccoli-cli

### ISSUE THREAD

**Issue by MajorBreakfast** [broccolijs/broccoli#112]
Broccoli is already split into many packages. Consider extracting all the cli stuff out of the core.

Some reasons:
- Separation of concerns
  - Separtation between broccoli core issues (e.g. watcher should not poll) and cli issues (e.g. force flag)
- Introduction of a nice minimal documented public API between core and cli (don't worry about breaking stuff once in a while, having it documented would still be better)
  - -> Cleaner integration of broccoli in ember-cli
- Lighter core
- Less dependencies for broccoli core

Some notes:
- Reading of the Brocfile should be in broccoli-cli, not in core

**Comment by stefanpenner** [comment]
We have done some of this, we will likely see more of this as I work on ember-cli + broccoli 1.0 integration.

I don't think this is a real issue, so closing it (but i suspect it will happen organically and transparently to most users)
