### ISSUE TITLE
Building multiple trees

### ISSUE THREAD

**Issue by digitalplaywright** [broccolijs/broccoli#126]
For a library I am making I would like to build a tree for the library distribution and another tree with modules defined purely for testing the library. Example modules used purely for testing are DS.Model, Ember.Object and Ember.Controller instances that are used to test the library API surface. Is there any documentation on how to build a library tree as well as a  tree for testing with Broccoli?

This is how I currently use Broccoli:
- https://github.com/digitalplaywright/ember-declarative-authorization

An example of a module I'd define purely for testing (will define more once I know how to do this):
- https://github.com/digitalplaywright/ember-declarative-authorization/blob/master/test/rules/rules.js

**Comment by stefanpenner** [comment]
This can be accomplished 2 ways:

* by utilizing broccoli as a library and having two separate build pipelines.
* by creating a broccoli-plugin, that explicitly writes to two separate directories.

I don't think this is an issue with broccoli, although some community plugin can likely make this much more ergonomic.
