### ISSUE TITLE
Broccoli watcher not firing change event

### ISSUE THREAD

**Issue by jeffjo** [broccolijs/broccoli#144]
I am instantiating and using a Watcher object in order to regenerate build output on file changes:

``` javascript
var tree = broccoli.loadBrocfile();
var builder = new broccoli.Builder(tree);
var Watcher = require('broccoli/lib/watcher');
var watcher = new Watcher(builder, { verbose: true });

watcher.on('change', function(tree) {
  //copy tree.directory to some output directory
});
```

Every once in a while, the watcher does not seem to be able to detect changes to the file system and the 'change' event is never fired. At this point, the only thing I can do is restart the script. This happens pretty infrequently, but it seems to happen more often when I'm away from my computer for a while.

Can anyone give me any pointers on how to debug this issue? I've tried sending `SIGUSR1` to the node process, but when I start the node debugger, it doesn't respond to any of the debugging commands.

**Comment by stefanpenner** [comment]
This problem hasn't come up for me in ages. New versions of node, new versions os's etc seem to have addressed this
