### ISSUE TITLE
Broccoli Serve stuck in build loop

### ISSUE THREAD

**Issue by ryanfields** [broccolijs/broccoli#173]
I'm new to Broccoli, so it's possible I've done something wrong.  Whenever I run `broccoli serve`, it endlessly loops over the build and does not allow anything to connect.  It just reports the build time and slowest trees over and over again.  I can't even break out of it with an interrupt.  I have to kill the process to stop it.  Running `broccoli build public` works fine.  I can load the static build and everything behaves as expected.

I'm using OSX 10.8.5, and I've tried this under Node 0.10 and 0.11 with the same result.

**Comment by stefanpenner** [comment]
I believe this is easier to address in 1.x as the watcher is part of core.

**Comment by stefanpenner** [comment]
Actually, broccoli 1.0 by default has moved the `tmpdir` out of the project root, which means by default this should already work more or less fine.

We should still bake in some auto-detection of this problem in to broccoli. But i'm tracking that here: https://github.com/broccolijs/broccoli/issues/94
