### ISSUE TITLE
Speed up with multi-threading?

### ISSUE THREAD

**Issue by danfinlay** [broccolijs/broccoli#174]
Hi there, I've got a pretty large app I'm working on, and I'm getting pretty long build times (~7000ms at times).  I was wondering if you thought it might be practical to use `child_process.fork()` or the `cluster` module to split the build process up among a computer's full processor.

[This blog post](http://blog.carbonfive.com/2014/02/28/taking-advantage-of-multi-processor-environments-in-node-js) is a pretty good introduction to the methods, I'm not adverse to trying to implement this myself, but I'd like some help grasping the `broccoli` architecture to help me do it.

Where, for example, is the individual file processing assigned?

**Comment by ohjames** [comment]
@flyswatter [sighjs](https://github.com/sighjs/sigh) is a build system much like broccoli that can also delegate tasks to multiple CPUs.

**Comment by flyswatter** [comment]
Nice to know!
