### ISSUE TITLE
`broccoli watch` could still be useful

### ISSUE THREAD

**Issue by jlongster** [broccolijs/broccoli#184]
I couldn't find a previous issue about this, so asking here. You say "no more `grunt watch`", but really to me broccoli just gets the dependency handling correct, and enables a much better "watch". Right now the broccoli-cli only supports `build` and `serve` commands; what harm would a `watch` command have, which is exactly like `serve` except instead of firing up a webserver, it writes the final file structure to dist on every change?

**Comment by fredrikekelund** [comment]
I agree completely that `broccoli watch` would be very useful! `broccoli serve` can complicate interaction with back-ends via relative URL's, so watch functionality together with livereload would be :ok_hand:

There is [broccoli-timepiece](https://github.com/rwjblue/broccoli-timepiece) which does provide a watch like command. It lacks livereload functionality though, but I'm trying to push for that here https://github.com/rwjblue/broccoli-timepiece/issues/9 And in any case, I do think the watch command should be a part of broccoli core.

**Comment by rwjblue** [comment]
@fredrikekelund - I disagree, `watch` should absolutely be facilitated by the core library but not bundled with it.  I believe that we should remove nearly all of the CLI code from this repo, and move that into broccoli-cli package (which is already required).

**Comment by fredrikekelund** [comment]
Sorry, my bad - that should be bundled with broccoli-cli, not necessarily with broccoli core. Basically what I was looking for was that it would make sense to be able to run `broccoli watch dest`. What do you think @rwjblue?

**Comment by stefanpenner** [comment]
I'n ember-cli we added `ember build --watch` and it has proved more useful then expected. We should likely consider added it here.

**Comment by fredrikekelund** [comment]
@stefanpenner with Watcher already being bundled in core and error reporting already in place for the build CLI command, I think this would be trivial to implement.

Would you accept a PR if I took a stab at it?

**Comment by chrmod** [comment]
@fredrikekelund I'm also on same issue, implementing https://github.com/broccolijs/broccoli/issues/331 step by step. 
If you're fine with it, I should be able to finish it before end of the week.

**Comment by fredrikekelund** [comment]
@chrmod ah, that's great! No worries, just wanted to offer my assistance
