### ISSUE TITLE
Left-over tmp files

### ISSUE THREAD

**Issue by jdhines** [broccolijs/broccoli#187]
Not sure if this should be in the ember-cli repo, but it seems to be related to builds.

Using Windows 7, ember-cli v. 40, broccoli-merge-trees v. 0.1.4.

Just yesterday, in trying to get my `ember server` build times lower than 100 seconds, I just removed everything in my /tmp directory, and even though I only have a couple dependencies and very few new files, there were over 6GB in that directory.

I'm guessing it's because every time I save a change I get an ENOENT error for something in /tmp, either "directory not empty" or "no such file or directory" so I have to just Ctrl+c and then restart the server.

There may be a number of separate issues here, and I'm perfectly open to the possibility that it may just be me since I'm fairly new to all this.

```
$ ember server
version: 0.0.40
ENOENT, no such file or directory 'c:\dev\star\tmp\tree_merger-tmp_dest_dir-gpm3q43C.tmp\fontawesome\src\cheatsheet.html
'
Error: ENOENT, no such file or directory 'c:\dev\star\tmp\tree_merger-tmp_dest_dir-gpm3q43C.tmp\fontawesome\src\cheatshe
et.html'
    at Object.fs.lstatSync (fs.js:679:18)
    at copyRecursivelySync (c:\dev\star\node_modules\ember-cli\node_modules\broccoli-static-compiler\node_modules\broccoli-kitchen-sink-helpers\index.js:142:21)
    at copyRecursivelySync (c:\dev\star\node_modules\ember-cli\node_modules\broccoli-static-compiler\node_modules\broccoli-kitchen-sink-helpers\index.js:148:7)
    at copyRecursivelySync (c:\dev\star\node_modules\ember-cli\node_modules\broccoli-static-compiler\node_modules\broccoli-kitchen-sink-helpers\index.js:148:7)
    at Object.copyRecursivelySync (c:\dev\star\node_modules\ember-cli\node_modules\broccoli-static-compiler\node_modules\broccoli-kitchen-sink-helpers\index.js:148:7)
    at c:\dev\star\node_modules\ember-cli\node_modules\broccoli-static-compiler\index.js:20:15
    at $$$internal$$tryCatch (c:\dev\star\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:470:16)
    at $$$internal$$invokeCallback (c:\dev\star\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:482:17)
    at $$$internal$$publish (c:\dev\star\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:453:11)
    at $$rsvp$asap$$flush (c:\dev\star\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:1531:9)
Livereload server on port 35729
Serving on http://0.0.0.0:4200
```

**Comment by newtonianb** [comment]
7 GB tmp directory here, Win 8.1

**Comment by stefanpenner** [comment]
> 7 GB tmp directory here, Win 8.1

i believe if it crashes, or unexpectedly quit, the async nature of node prevents the typical cleanup from happening....

**Comment by newtonianb** [comment]
I do remember numerous times killing it CTRL+C throughout development as the auto page refresh seemed frozen and kept loading with no end in sight, so probably during these times no cleanup occurred. In that case my issue would be what's causing these refresh freeze.

**Comment by whitmanc** [comment]
Is this fixed, since the issue is closed? Or is there a solution that I am missing? Also happening on OS X. 

I am not using ember.

**Comment by joliss** [comment]
Normally Broccoli and Ember CLI clean up everything on Ctrl+C, but I've noticed that if you hit Ctrl+C in the middle of an initial build, it will leave leftover files.

In Broccoli core, the SIGINT (Ctrl+C) handler that runs the cleanup seems to be set up *after* the initial build. That's clearly a bug. The handler furthermore isn't set up at all when we run `broccoli build` - but it probably should.

In Ember CLI, the SIGINT handler is set up earlier, before the initial build. Yet strangely, the leftover file problem still occurs. We'll have to investigate.

I'd like to leave this open for now, and revisit the cleanup handling code once the upcoming [API change](https://github.com/broccolijs/broccoli/blob/master/docs/new-rebuild-api.md) is finished, because that API change will centralize the tmp dir handling in Broccoli core and simplify things considerably. Here is what we'll want to address then:

* Handle SIGINT properly and consistently.

* Even with SIGINT handled, there will probably be cases where we fail to clean up because Broccoli hard-crashes (e.g. SIGKILL), so it might be worth thinking about trying to automatically clean up tmp dirs from previous invocations of Broccoli as well.

**Comment by whitmanc** [comment]
@joliss Thanks for checking it out. If I have the time / ambition to do it, I will try to look into broccoli internals to see if I can find a way to clean up tmp dirs from previous invocations (this is the one getting me).

**Comment by stefanpenner** [comment]
> In Ember CLI, the SIGINT handler is set up earlier, before the initial build. Yet strangely, the leftover file problem still occurs. We'll have to investigate.

i think we abort prematurly still in-afew places.

**Comment by blimmer** [comment]
I run into this all the time. I don't know if it's Atom that holds onto the `tmp` directory, but every few days my `tmp` directory grows to multiple gb in size and builds crawl to multiple minutes.

**Comment by blimmer** [comment]
Here's what it looks like normally:
```
Build successful - 8138ms.

Slowest Trees                                 | Total
----------------------------------------------+---------------------
SassCompiler                                  | 2453ms
Funnel: App JS Files                          | 1479ms
ES6: App Tree                                 | 607ms
Concat: App                                   | 552ms
Concat: Vendor                                | 533ms
TreeMerger (appAndDependencies)               | 453ms

Slowest Trees (cumulative)                    | Total (avg)
----------------------------------------------+---------------------
SassCompiler (1)                              | 2453ms
Funnel: App JS Files (1)                      | 1479ms
ES6: App Tree (1)                             | 607ms
Concat: App (1)                               | 552ms
Concat: Vendor (1)                            | 533ms
TreeMerger (appAndDependencies) (1)           | 453ms
```

and when :hankey: hits the fan:
```
Build successful - 452375ms.

Slowest Trees                                 | Total
----------------------------------------------+---------------------
Concat: App                                   | 106094ms
Funnel: App JS Files                          | 56310ms
AutoprefixerFilter                            | 45758ms
Concat: Vendor                                | 34728ms
ES6: App Tree                                 | 34644ms
TreeMerger (appAndDependencies)               | 30993ms

Slowest Trees (cumulative)                    | Total (avg)
----------------------------------------------+---------------------
Concat: App (1)                               | 106094ms
Funnel: App JS Files (1)                      | 56310ms
AutoprefixerFilter (1)                        | 45758ms
Concat: Vendor (1)                            | 34728ms
ES6: App Tree (1)                             | 34644ms
TreeMerger (appAndDependencies) (1)           | 30993ms
Babel (6)                                     | 26097ms (4349 ms)
```

**Comment by bucaran** [comment]
@stefanpenner  @joliss Hi. So, what's the status on this issue? Comments?

**Comment by cbornhoft** [comment]
Having the same problem. `/tmp` continuously fills and is never cleaned on `ember server` exit.

Windows 7 x64 SP1

**Comment by bucaran** [comment]
@cbornhoft I am not sure about Windows 7, but make sure to wait until the prompt is restored after you end the server with `<ctrl> c`. `ember-cli` should clean up these files during exit, but it can take up severl seconds depending on your system, so if you try to hit the exit sequence more than once, it might kill the process so the tmp files never get deleted.

**Comment by cbornhoft** [comment]
@bucaran You mean `Ctrl+C` and then the prompt `Terminate batch job (Y/N)?` yeah?

I always follow the prompt and after entering `Y` the Powershell window exits completely. I believe that would be because I'm running the server from a `.ps1` script. Would that affect it?

**Comment by bucaran** [comment]
> You mean Ctrl+C and then the prompt Terminate batch job (Y/N)? yeah?

Yes.

If you are waiting and still not getting your tmp files deleted, then there is a problem indeed.

**Comment by cbornhoft** [comment]
Thanks @bucaran seems this is an issue for me then too.

**Comment by cbornhoft** [comment]
If anyone is interested, this is my updated `.ps1` script to start an `ember server` and empty `/tmp` on close for Windows:

    cd \path\to\ember\project
    ember server --proxy http://api.example.com
    Read-Host -Prompt "Confirm Exit"
    rm -r tmp\*

**Comment by Siyamala** [comment]
Do we have any update on this issue?

**Comment by kensei62** [comment]
On my Mac, the tmp directory is cleaned up except when I run "ember test --server". When I exit the test process by pressing 'q', the contents of tmp are not deleted.

**Comment by stefanpenner** [comment]
@kensei62 i believe that is do to something doing a premature process.exit. Which version of ember-cli and testem?

**Comment by kensei62** [comment]
Output from 'ember --version':
    version: 1.13.13
    node: 0.12.7
    npm: 2.14.10
    os: darwin x64

testem appears to be version 0.9.11

**Comment by stefanpenner** [comment]
Try latest beta, as we are now at 1.x testem. If I recall we fixed a spurious exit related to this recently.

**Comment by ryanhend** [comment]
I noticed the tmp folder was full on my windows machine, 20k odd folders. 
So I cleansed it. Then I found a whole lot of files under app were deleted!

I just lost 2 days worth of work

I delete tmp files, so tool deletes project, WTF

**Comment by stefanpenner** [comment]
for more recent ember-cli users this problem is largely fixed. The problem of mid-build exists resulting in tmpdir's sticking around.

For broccoli 1.0+ it appears  to have additional  machinery to handle this: https://github.com/broccolijs/broccoli/blob/0bc034c5840c3e54e70a2a60153dc71ed41c8afd/lib/builder.js#L20. I also plan to forward port ember-cli related improvements: https://github.com/broccolijs/broccoli/pull/312

Anyways this is likely good to close
