### ISSUE TITLE
Windows performance

### ISSUE THREAD

**Issue by eibrahim** [broccolijs/broccoli#188]
Sorry if this is the wrong place but I really want to use ember cli for my project but the performance on windows is unusable and it's because of Broccoli.  

Any updates on improving performance on windows or is there anything I can do to help?  If you point me to the right place I can try and optimize it.  Thanks.

**Comment by oligriffiths** [comment]
This should be solved by the removal of the `tmp` directory from the project directory. Closing this issue now, please reopen if this is still a problem.

**Comment by stefanpenner** [comment]
I believe @thoov’s memoization should have also helped in many scenarios for windows users
