### ISSUE TITLE
Too Many Open Files

### ISSUE THREAD

**Issue by kylecordes** [broccolijs/broccoli#191]
I am unsure of which plugin triggers this, so I'm putting it here in the main project tracker.

On OSX at least, it is easy to accidentally trigger a "too many open files" OS error. The fix at first appears to be to adjust this number upward; but with a little experimentation I found that Broccoli or one of its plugins opens and keep open *all* of the files it sees, at the same time.

This is perhaps feasible for a project source tree, as long as noone tries to use Broccoli with a large project. But even with a small project that happens to use Bower (or worse, NPM) in such a way that Broccoli can see bower_components or node_modules - in which case there can easily be 2000, 5000, 10000 files sitting there.

I think it is infeasible for Broccoli or most plugins (aside from those which will only ever be shown a small numbers of files) to open all the files they can see at the same time.

**Comment by joliss** [comment]
I'll go ahead and close this, but if people see more such errors, it would definitely be useful to get reports about it! :)
