### ISSUE TITLE
How do I integrate a handlebars template processor?

### ISSUE THREAD

**Issue by kristianmandrup** [broccolijs/broccoli#200]
I created the following Broccoli template filter

https://github.com/kristianmandrup/broccoli-i18n-template

But I have no idea how to add it into my `Brocfile.js`, without recreating the whole process for how the app tree is created. How do I "hook it in" correctly? The filter is not called simply by installing it as an npm package... We really need some better documentation.

Thanks ;)

**Comment by stefanpenner** [comment]
I think this question was more ember-cli related. As it dictates how the pipeline is assembled. Broccoli merely provides the primitives.

I will gladly reopen if my interpretation is incorrect.
