### ISSUE TITLE
Windows failing tests

### ISSUE THREAD

**Issue by simi** [broccolijs/broccoli#203]
There are four random failing tests on Windows (tested locally and via Win CI). You can see some examples on [AppVeyor](https://ci.appveyor.com/project/joliss/broccoli/build/job/u4ji84w7gfs4xhk1).

All four failing tests are captured in my [gist](https://gist.github.com/simi/6c6dc867796551a1f50b).

It looks like some timing or performance issue.

**Comment by stefanpenner** [comment]
they are green, @joliss can you close
