### ISSUE TITLE
How to do incremental rebuilds if previous tmp folder is gone?

### ISSUE THREAD

**Issue by rickharrison** [broccolijs/broccoli#206]
I am working on a plugin to do incremental rebuilds with `browserify`. I'm having trouble figuring out how to implement the rebuilds.

I have been hacking around with the internals used by `watchify` to accomplish faster rebuilds. However, I have run into a problem where the `browserify` cache points to the file in the old /tmp/ folder, which no longer exists. I then get an error like this:

```
Error: ENOENT, open '/Users/rickharrison/projectname/tmp/replace_filter-tmp_dest_dir-k8h7XRHN.tmp/routes/sign-out.js'
  at Error (native)
```

Do you have any suggestions on how to get around this or a better approach to incremental rebuilds?

**Comment by stefanpenner** [comment]
mixing two different pipelines isn't going to be much fun. I have some ideas to make it better, but likely not a short-term thing.

For anyone looking for broccoli + browserify integration then: https://github.com/eploko/broccoli-watchify may help. I need to fix it for 1.0, but that should happen soonish. (ping me if it doesn't)
