### ISSUE TITLE
add appveyor bage

### ISSUE THREAD

**Issue by stefanpenner** [broccolijs/broccoli#221]

**Comment by stefanpenner** [comment]
@joliss i am unable to add this badge, as i do not have commit to this project (or appveyor) so I cannot get to the "badges" pane 

https://ci.appveyor.com/project/joliss/broccoli > settings > bages > "master branch status badge" > "Branch sample markdown code"

**Comment by joliss** [comment]
Thanks Stef; I've added the badge and also added you as a committer.

**Comment by stefanpenner** [comment]
thanks :)

**Comment by stefanpenner** [comment]
its silly that the badge URL isn't public
