### ISSUE TITLE
Broccolijs.com

### ISSUE THREAD

**Issue by folz** [broccolijs/broccoli#222]
I had some free time and noticed broccoli doesn't have an official website so I made http://broccolijs.com. If it's something you'd like to use, I'm happy to turn over the repo and registration to the broccoli project.

![screen shot 2014-12-02 at 21 36 58](https://cloud.githubusercontent.com/assets/299281/5352497/3ccbb6a6-7f35-11e4-8c70-e38e731099e5.png)

**Comment by folz** [comment]
Still looking for a hand with the official site, or is this off the table for now?

**Comment by trek** [comment]
Part of the difficulty I think exists is that the target audience for who I'd like to convince using Broccoli is a slightly higher level of abstraction over broccoli core. I know https://github.com/stefanpenner/broccoli-stew/ adds many of the more "userland" niceties that broccoli itself doesn't need to have.

So, I'd think we'd hold off until there is a more userland friendly story. One way to think of it is Kernel:Linux::Broccoli:broccoli-stew

The kernel is obviously super important but the number of people who be geeked about it (and need to be sold on it) is much smaller to, say, Linux as a whole

**Comment by stefanpenner** [comment]
ya, the broccoli kernel is a good way to describe it.

**Comment by trek** [comment]
and of course the marketing site is really about the broccoli ecosystem, which we're still massaging the exact form of. I think grunt and gulp have an easier time because more of their ecosystem is built into their core.

**Comment by folz** [comment]
Gotcha. Would you object if I wrote up some Broccoli use cases (similar to Rust By Example) and released the website as unaffiliated with you all? Or is there another way I could help you release some quality documentation for broccoli, broccoli-stew, or another related project? I'm really geeked out about broccoli and want to see it succeed.

If not, I totally understand and I'll close the issue.

**Comment by joliss** [comment]
No that's great, definitely do make documentation. I'll be happy to help too. I haven't been terribly responsive, but trying to rectify this by allocating my Thursdays to Broccoli.

There's some upcoming changes to the API that will affect slightly how Brocfiles are written (the "rebuild" branches, probably landing in Broccoli 0.14), maybe it's worth waiting with the examples till that is released.

Is https://github.com/folz/broccoli-site the source code for http://broccolijs.com/? Do you maybe want to slap an MIT license on it to make it open source?

> If it's something you'd like to use, I'm happy to turn over the repo and registration to the broccoli project.

As for the repo, I'm happy to pull this into the broccolijs GitHub namespace and add you as a collaborator here.

As for the domain registration, I don't particularly care who owns and runs it. Do you *want* me to take it over? If so, let me know and I'll figure out how to get it transfered to my preferred registrar (Dyn).

**Comment by indus** [comment]
if you need a free domain you could have a look at [JS.ORG](http://js.org)

**Comment by lan3jur** [comment]
It's great to read all this, but, in my humble opinion, you're eliminating 1 type of audience: the absolute beginner (people like me). I used gulp for a long time but for reasons similar to the reasons why broccoli was created in the first place, I started to like it less and less.
I know you people are all excellent coders, but sometimes, the 'language' you use gets people like me confused :)
So, if I may make a small suggestion, I think the official website could use some 'community' part. I have quite some ideas on how to fill this with content, so I wanted to check if maybe there's a way we can slowly implement this step by step or if it would be more beneficial if I created my own and keep you guru's *wink* updated on progress, additions, etc.. and ask for approval before going live.
Would love to hear some thoughts on this.
Thanks!

**Comment by folz** [comment]
Just was pinged about this. I'm still happy to transfer it - the domain is registered with NearlyFreeSpeech.net and the site is hosted with NFSn as well. To transfer ownership, you can either create an account at NFSn and I'll request an internal transfer, or we can coordinate a cross-registrar transfer. It looks like reregistration is on Dec 8th, so it'd be great to have this done by then.

Either way, we should coordinate by email so I don't have to post private domain transfer codes on github. My email is my first name at my full name dot com.

**Comment by stefanpenner** [comment]
@joliss if you don't have time, I'll gladly handle this.

**Comment by folz** [comment]
Got an update email from my registrar that Dec 8th is in 10 days. Let me know what you all want to do.

**Comment by joliss** [comment]
@folz I'd like to try and take over the domain registration. My registrar is Dyn, and they have some instructions here: https://help.dyn.com/domain-registration/transferring-a-domain-name-registration-to-dyn/ Can you unlock the domain for me and send me the EPP Authorization Code (joliss42@gmail.com)? I'm not too worried about the DNS disruption bit they mention. I'll probably set up a temporary redirect to the README until we update the website based on your [broccoli-site](https://github.com/folz/broccoli-site) repo.

@stefanpenner I'd still definitely like some help with the website itself! :)

**Comment by stefanpenner** [comment]
> @stefanpenner I'd still definitely like some help with the website itself! :)

Sounds good! How should we proceed ?

**Comment by myfreeweb** [comment]
The website still mentions "latest stable version of node (**v0.10.x**)"…

**Comment by gabrielcsapo** [comment]
transferring the website makes sense!

**Comment by gabrielcsapo** [comment]
I have a PR to update the website https://github.com/folz/broccoli-site/pull/6 @myfreeweb @folz @stefanpenner

**Comment by folz** [comment]
While I appreciate your PR @gabrielcsapo, I'm going to let the Broccoli team make any updates. Jo has ownership over the website registration and DNS now, and while it currently points to my existing site out of convenience for them, I'm not involved enough (aka, at all) with this project to feel comfortable changing the content without their knowledge/approval.

(In retrospect, I wish me 3 yrs ago had just registered the domain and turned it over so that nobody could squat the dot-com, instead of making a website as well. Seems to have caused more headaches than benefits.)

Going to close this PR since Jo owns the domain; if the Broccoli team also wants me to transfer the [folz/broccoli-site](https://github.com/folz/broccoli-site) repo I'm down, but I feel like it'd be easier to start a new website from scratch at this point.

**Comment by gabrielcsapo** [comment]
@joliss thoughts on taking over the broccoli site?
