### ISSUE TITLE
How to act on output file changes?

### ISSUE THREAD

**Issue by mohamnag** [broccolijs/broccoli#227]
So I wrote this plugin on Friday: https://www.npmjs.com/package/broccoli-splitter
The main reason for that is the fact I have to split my final `index.html` file into two files which are then integrated into the rest of pages in a relatively large portal. The problem is that as soon as I watch the `dist` folder (because `index.html` which I have to take is the final one), there will be a cyclic process which triggers the build in an infinity loop.

is there a way to tell broccoli only to watch one file (`dist/index.html`) and not the whole dir? I can not find any thing similar online. or maybe some other way to get my hands on the output of the process which produces the `dist/index.html` file, before this file is written into disk?

**Comment by joliss** [comment]
The `dist` directory is not intended to be watched by Broccoli - trying it will inevitably lead to chaos.

It seems that what you're trying to do is take (some of) the output of Ember CLI's default stack, and emit something new based on it, right?

I haven't used Ember CLI much, but I assume you can get at the output (root) tree object somehow, right? I'd then pass that tree to other plugins like broccoli-splitter, and e.g. merge the results to get a new output tree.

**Comment by stefanpenner** [comment]
> is there a way to tell broccoli only to watch one file (dist/index.html) and not the whole dir? I can not find any thing similar online. or maybe some other way to get my hands on the output of the process which produces the dist/index.html file, before this file is written into disk?

not really, file-watching is OS implemented on a per DIR or per tree of dir basis.

> I haven't used Ember CLI much, but I assume you can get at the output (root) tree object somehow, right? I'd then pass that tree to other plugins like broccoli-splitter, and e.g. merge the results to get a new output tree.

the tree exported in the Brocfile would be this tree.
