### ISSUE TITLE
Allow specifying Brocfile path and CWD

### ISSUE THREAD

**Issue by jnorth** [broccolijs/broccoli#230]
Currently the `Brocfile.js` and working directory are not able to be set from the CLI, and there doesn't seem to be a clean, side-effect free way to build manually.

I'd love to see two things:
#### CLI options

`--broc-file` to specify which file to load as the `Brocfile.js`.

`--cwd` to specify which path the Brocfile trees should be relative to.
#### Manual Building

Ideally we could set the root path when creating a new builder instance `new broccoli.Builder(tree, cwd);`. Any paths in the `tree` would be relative to `cwd`.

Additionally, we could set the output path when calling `broccoli.build(outputPath)`. This would handle all of the building, the `copyDereferenceSync`, and any cleanup.

**Comment by stefanpenner** [comment]
:+1:

**Comment by rwjblue** [comment]
This project should be focused on the actual build process (essentially just `lib/builder.js`), ideally everything else should be moved to broccoli-cli or other associated projects.  I am not in favor of adding any more complexity here.

That being said: I absolutely think these options should exist. I just think they belong in broccoli-cli, and that we should move `lib/cli.js` into that library.

I'll try to chat with Jo about her thoughts on Thursday...

**Comment by stefanpenner** [comment]
@rwjblue 

findUp in builder needs to be configured correctly
https://github.com/broccolijs/broccoli/blob/master/lib/builder.js#L136

**Comment by rwjblue** [comment]
@stefanpenner - What is incorrect about it?

**Comment by stefanpenner** [comment]
@rwjblue  it assumes cwd

**Comment by rwjblue** [comment]
@stefanpenner - There is no way to provide an alternate CWD anyways.  If we add a `--cwd` flag to broccoli-cli, then the Builder would be updated to support alternate CWD's.

**Comment by stefanpenner** [comment]
@rwjblue yes, that is what I'm pointing out

**Comment by joliss** [comment]
> Ideally we could set the root path when creating a new builder instance `new broccoli.Builder(tree, cwd);`. Any paths in the `tree` would be relative to `cwd`.

This sounds generally reasonable, but we'd want to make sure that the interaction with the watcher is well-specified, so that the watcher doesn't get confused when `cwd` isn't `'.'`.

Maybe let's revisit this once the builder is rewritten, at the end of the current [API change]. At the moment it's all a bit messy.

**Comment by ilikebits** [comment]
:+1:, would love to have a way to specify production vs. development Brocfiles.

**Comment by stefanpenner** [comment]
I've added this to: https://github.com/broccolijs/broccoli/issues/331 We can track this there
