### ISSUE TITLE
Add opt-out for asset browsing.

### ISSUE THREAD

**Issue by rwjblue** [broccolijs/broccoli#231]
This was added in #160, but due to directories being served it is not possible to have top-level history support based routes that happen to correspond with folders in the build output.  

Specifically, you cannot have an `assets` route in Ember + EmberCLI, because the broccoli middleware will serve a listing of the `assets/` directory instead.

**Comment by joliss** [comment]
Hm... If your Ember app has an `/assets` route, but the assets live at `/assets/*`, then it seems you'll still generally have the same problem when you deploy to production, won't you? I realize that in principle you could make it work in production, but we (ember-cli) don't control the production environment, so it seems quite error-prone...

I wonder if it might not be acceptable to just say "don't do that".

**Comment by joliss** [comment]
I'm still dubious whether this is actually good idea, but I'm OK with adding an option to enable/disable directory browsing (default-true maybe?).

**Comment by joliss** [comment]
Fixed by a0c9940.
