### ISSUE TITLE
[Memory Leak] allTreesRead grows without bounds

### ISSUE THREAD

**Issue by bjornstar** [broccolijs/broccoli#236]
Original Issue: https://github.com/ember-cli/ember-cli/issues/3305

If I leave my ember server running for a few hours it begins to consume a large amount of memory. I'm sitting at 850MB right now. Looking at the heapdumps I can see broccoli holding onto every copy of every tree ever created since the server started. Every time a file changes, `allTreesRead` gets a whole new copy of my application. The old copies never get cleaned up.

**Comment by johnnyshields** [comment]
:+1:

**Comment by johnnyshields** [comment]
Is anyone looking at this?

**Comment by joliss** [comment]
Yup, this will go away with an upcoming refactoring. Bear with us in the meantime please ;-)

**Comment by johnnyshields** [comment]
@joliss thanks, our team will be looking forward to it.

**Comment by JDillon522** [comment]
Has this been resolved? My team is noticing this as well. I've seen my used memory go from high 500mb to 1.2gb in the past day

**Comment by joliss** [comment]
No, it's not yet resolved, but the refactoring is getting closer :)

**Comment by chris-pauley** [comment]
Any updates?

**Comment by joliss** [comment]
This is fixed in the Broccoli 1.0 beta.

**Comment by joliss** [comment]
Here's how to upgrade to 1.0: https://github.com/broccolijs/broccoli/blob/master/docs/broccoli-1-0-plugin-api.md#for-broccoli-users-upgrading-to-broccoli-1x
