### ISSUE TITLE
tutorial

### ISSUE THREAD

**Issue by sgiaccio** [broccolijs/broccoli#245]

**Comment by timmfin** [comment]
I'm not sure that opening a one word issue is that helpful. Yes Broccoli could use more learning docs and tutorials, but it would be helpful if you could more specifically describe what you are looking for and/or what was confusing to you.

And BTW, have you seen https://github.com/broccolijs/broccoli-sample-app? It isn't exactly a tutorial but a decent starting place.

**Comment by sgiaccio** [comment]
Sorry, that was supposed to be a google search, I don't know how it ended up being an issue on github. Thanks for the info by the way.

**Comment by joliss** [comment]
Haha, closing then :)
