### ISSUE TITLE
Broken compatibility for modules that already used the name `rebuild`

### ISSUE THREAD

**Issue by ef4** [broccolijs/broccoli#246]
It looks like broccoli is trying to detect new-API compatibility based on the presence of a `rebuild` function. But `rebuild` was already a pretty obvious name to use as part of a module's implementation. See for example https://github.com/ef4/ember-browserify/issues/25

I don't have a solution to propose, I realize the upgrade path is tricky. But I'm sharing this so more people are aware of the pitfall.

**Comment by rwjblue** [comment]
We need to break out the compat system into a package that plugin authors can use so that their plugins are compatible with older Broccoli versions (including 0.13).

Doing that would allow authors to move to the new paradigm while still supporting older Broccoli versions than those that include the compat layer.

Specifically, things like ember-browserify can update to the new API and still support ember-cli 0.1.x (which uses Broccoli 0.13).

**Comment by ef4** [comment]
As an idle observation: this is the kind of scenario that ES2015 symbols will be able to help with once they're available on all the relevant platforms. Addons could unambiguously express their intent to implement the new API by implementing it with a broccoli-exported symbol, rather than a string.

**Comment by joliss** [comment]
> We need to break out the compat system into a package that plugin authors can use so that their plugins are compatible with older Broccoli versions (including 0.13).

Good point.

> As an idle observation: this is the kind of scenario that ES2015 symbols will be able to help with once they're available on all the relevant platforms. Addons could unambiguously express their intent to implement the new API by implementing it with a broccoli-exported symbol, rather than a string.

Very nice. One missing piece is the package manager: At the moment, if a plugin were to depend on Broccoli, npm would provide it with a duplicate different version of Broccoli, so the symbol wouldn't match. We're basically waiting for someone to write Ruby bundler+rubygems, but for Node.

**Comment by joliss** [comment]
And on the issue of not accidentally breaking plugins that have an internal `rebuild` function: I don't have a solution either :( Wish it was fixable, but unsure whether it's possible.

**Comment by stefanpenner** [comment]
> npm would provide it with a duplicate different version of Broccoli, so the symbol wouldn't match.

yes, NPM basically breaks symbols. But it doesn't break branding.

```
export default {
  rebuild: Broccoli.rebuild(function() {

  })
}
```

where `Broccoli.rebuild` decorates the returning function with `isBroccoliRebuild`

**Comment by ef4** [comment]
> At the moment, if a plugin were to depend on Broccoli, npm would provide it with a duplicate different version of Broccoli, so the symbol wouldn't match. 

Ah yes, my list of "things that are broken about npm" overflowed and I forgot about that one.

**Comment by rwjblue** [comment]
@joliss - I am working to extract the compat API, broccoli can use it the same way, but so can authors. Should have a package out this afternoon...

**Comment by joliss** [comment]
So I think this particular issue isn't fixable anymore, but at least the [new plugin API](https://github.com/broccolijs/broccoli/blob/master/docs/broccoli-1-0-plugin-api.md) is designed to prevent similar things from happening with future API extensions.
