### ISSUE TITLE
Usage of tmp dir is not documented

### ISSUE THREAD

**Issue by dfernandez79** [broccolijs/broccoli#252]
Aparently broccoli needs to create a tmp directory to work, but that is not documented anywhere in the README, and caused me a lot of headaches as a newbie :)

I run into this problem:
- Create a simple Brocfile.js that uses the babel transpiler
- Run `broccoli build tmp` to transpile the sources into tmp. You will get an error that `tmp` already exists. A tmp directory is created.

At first I though that the problem was in the babel plugin. But after looking into the code, and searching in GitHub for reported issues. I give a last try by using a different build target directory and it worked :)

That should be documented, or at least the error message should be different. Looking into the issues it seems that `tmp` dir is used by broccoli, but that is not documented :( and it was my newbie mistake to use that name as output

**Comment by kylecordes** [comment]
Perhaps in addition to a bit of documentation, it would be helpful if broccoli builds would block you from using names that obviously will not work, like "tmp" as discovered here. In broccoli's defense, if you follow the documentation and try something like "broccoli build the-output", it will work painlessly.

**Comment by stefanpenner** [comment]
@dfernandez79 ya great feedback. This has been addressed, I don't recall exactly when but I do know the broccoli 1.0 code does not have this problem
