### ISSUE TITLE
Is it possible to serve built result in memory via "broccoli serve" cmd?

### ISSUE THREAD

**Issue by jinyangzhen** [broccolijs/broccoli#254]
In our case, we are using "broccoli serve" as kind of CDN host that is primarily serving for static-file-watch-and-rebuild process in DEV env. Since our product has thousands of small JS/CSS files separated into several modules, the dev build process is designed to only containing those time-efficient steps like less2css, concatenate and source-map generation.

Thanks for broccoli's incremental build strategy - the developer can almost get an up-to-date build result within 2~5 seconds. That means in most cases developer can hardly notice the difference whether a static resource is served by broccoli with live watch or directly from disk without any live-watch. This give us good developing experience.

I noticed Broccoli still export build result to a tmp directory and serve from tmp directory, so i am curious if this could be improved further through an in-memory building and serve built content directly from memory too. I guess this can give  even better response time when using Broccoli as a resource hosting server, maybe hundreds millisecond in our case

**Comment by joliss** [comment]
In the future it will be possible to configure the tmp dir and put it on a RAM disk, like `/dev/shm`. I'm unsure how much improvement this will actually bring, but it's worth a try for sure.

> I guess this can give even better response time when using Broccoli as a resource hosting server

Just to make sure, this is for local (intranet) development, yes? I don't recommend exposing the Broccoli server in production; it isn't written with that kind of security in mind.

**Comment by rwjblue** [comment]
> In the future it will be possible to configure the tmp dir and put it on a RAM disk

This is possible today, take a look at [ember-cli-ramdisk](https://github.com/ExpressCheckout/ember-cli-ramdisk).

**Comment by jinyangzhen** [comment]
Thanks both! Ramdisk does enlighten me.

I did a small test by following up the idea and mklink a ramdisk to the "broccoli tmp" directory in windows (via Dataram utility mention at https://github.com/ExpressCheckout/ember-cli-ramdisk/issues/2), it looks like there wasn't much performance gain. It looks to me the bottleneck may not be in I/O for broccoli in Windows (I have ensure broccoli is using symbolic link instead of falling back to copying).

Comparing to Windows, i can achieve 4x faster in OSX with a similar hardware spec. 

Having said that, this is only my personal experience in my env. maybe others would vary....

**Comment by TomGault** [comment]
I've had the exact same experience.  Windows, SoftPerfect RAM Disk of tmp directory, moderate speed improvement but not coming anywhere near my Mac-using co-workers.

**Comment by kylecordes** [comment]
I noticed this old issue, it had been an inconvenience when I started using broccoli a couple of years ago and noticed that my Windows coworkers have a dramatically slower experience. From the discussion here year ago, it sounds like a RAM disk does not help anywhere near as much as one might hope.

I suspect broccoli is about to receive a large influx in (indirect) users, as it is used underneath Angular-CLI (built on Ember CLI). Many of them may have something to say about performance on Windows. This might be a good time to continue the discussion about how to make it excellent.  An improvement would course also make it even more excellent than it already is on Linux or OSX, where (in the example in front of me) creating a few thousand files on disk happens quite quickly.

(I believe a dream solution be to eliminate the use of disk entirely; however, this would involve replacing the interface between broccoli and every plug-in with something more complex than location on a disk. So I think that as far out of scope. I wonder if anyone has ideas of lesser scope that could help.)

**Comment by TomGault** [comment]
Someone who has time should try running profiling very simple commands on differently-shaped file trees to see if there are any low-hanging fruit.

For example, it may be that broccoli on Windows is slow at simply enumerating the names of files in a directory, then the `node_modules` sub tree is going to give it a heart attack.  If this were the case it might be possible to change how filtering is handled so that more of the tree can be culled before enumerating it.

I have no idea if this example is actually the case, just giving an example of what someone (who has more time than me) might be able to find!  :)
