### ISSUE TITLE
Incremental Rebuild to Disk

### ISSUE THREAD

**Issue by francoislaberge** [broccolijs/broccoli#255]
hi,

How do you do something like ```broccoli serve``` that rebuilds things incrementally to a folder on disk? My team's use case is working on an atom-shell app and wanting to use es6 without build pauses between changes. Our gulp based watching work flow went from near instantaneous to about 3 seconds now, and it's adding up to being annoying.

Any help would be appreciated,
Francois

**Comment by joliss** [comment]
There is no built-in `watch` command (yet) to build into a folder, but try [broccoli-timepiece](https://github.com/rwjblue/broccoli-timepiece).

**Comment by francoislaberge** [comment]
Thanks! Will check that out!
