### ISSUE TITLE
Rebuild upon file updates don't work through Vagrant Machine (even though file is updated)

### ISSUE THREAD

**Issue by tolgaek** [broccolijs/broccoli#257]
I have a vagrant machine set up and I develop locally (on host machine) and it gets synced to guest machine which is running ubuntu (using `ember serve`)

I can see the file's on the vagrant machine is updated but no build is triggered. If I modify a file directly on vagrant, it does get triggered though

**Comment by achan** [comment]
@tolgaek Did you ever get this working? I'm encountering the same thing.

**Comment by joliss** [comment]
Ember CLI doesn't use Broccoli's built-in watcher (which is quite primitive and should work on any FS) but rather broccoli-sane-watcher, which in turn uses [sane](https://github.com/amasad/sane). Maybe you can create a bug report for them, with a few more details?

**Comment by kaanbasal** [comment]
@tolgaek did you try `ember serve --watcher polling`?

**Comment by stefanpenner** [comment]
> @tolgaek did you try ember serve --watcher polling?

This will absolutely solve the problem.  

Now that broccoli 1.x also provides a watcher, it will also need to expose `--watcher`: Tracking that here: https://github.com/broccolijs/broccoli/issues/331
