### ISSUE TITLE
[FEATURE REQUEST] - broccoli init command

### ISSUE THREAD

**Issue by cowboyd** [broccolijs/broccoli#259]
I think it would kickstart people getting started using Broccoli directly if you could `cd` into a project directory and run `broccoli init` to setup a simple brocfile setup best practices in place. Sure, putting together the pieces from the README isn't that hard, but little helping hand would be nice too.

Example:

1. cd my-project
1. broccoli init
1. creates `lib` directory if it doesn't exist already.
1. creates Brocfile.js with simple `module.exports = 'lib'` and explanation

If this seems like a good idea, I'd be happy to give this a shot if anybody could point me in the right direction.

**Comment by joliss** [comment]
I think `init` is very useful for tools like Ember CLI, but for a bare-bones library like Broccoli, where the "minimum viable Brocfile" is `module.exports = 'lib'` as you point out, it might be easier to write documentation rather than adding code.

**Comment by cowboyd** [comment]
That's fair.

**Comment by lan3jur** [comment]
Imho it would be pretty awesome if it would be possible to make something like slush with broccoli. Or tell me what's the best place to ask very newbie questions ;-)

**Comment by joliss** [comment]
> Imho it would be pretty awesome if it would be possible to make something like slush with broccoli.

I'm all in favor! Basically I'd like to see more tools like Ember CLI, not just for Ember but for other frameworks and for frameworkless development too.
