### ISSUE TITLE
Tmp dir naming

### ISSUE THREAD

**Issue by joliss** [broccolijs/broccoli#262]
/cc @rwjblue, @stefanpenner, @caitp

When tmp dir handling is centralized, what do we want the names of the temporary directories to be?

Currently we have names like `babel-tmp_dest_dir-kbIdaoyR.tmp`, which isn't terribly user-friendly.

Are we going to do something like this (numbered by order of execution), or should we try to put more information into the names?

```
01-babel
02-babel
03-babel
04-babel
05-sass
06-sass
07-funnel
08-jshint
09-merge-trees
10-merge-trees
11-merge-trees
```

If we wanted to put more information (like `01-babel-lib`, `02-babel-vendor`), it would likely have to be supplied by the build definition (like `Brocfile.js` or [`ember-app.js`](https://github.com/ember-cli/ember-cli/blob/e120525d1bd70f3e06b92648f21ab055d5f311b5/lib/broccoli/ember-app.js)). I have no idea whether this is doable in practice. But if we plan on doing this, I'd like to take it into account for the API.

Semi-relatedly, currently everything is in `./tmp`, but we likely want to change this. I'm thinking maybe `/tmp/broccoli.$PID/trees/01-babel` for the output directory of the first plugin, and `/tmp/broccoli.$PID/caches/01-babel` for its cache directory. Alternatively, we could use `/tmp/broccoli.$PID/01-babel/{out,cache}`, and create symlinks at `/tmp/broccoli.$PID/01-babel/in-{0,1,2,3,4,5}` pointing to the input directories; those symlinks would not be used by Broccoli, but created for the convenience of people inspecting the tmp dirs.

**Comment by caitp** [comment]
Ordering the temp directories by use order would work well for us. We don't care a whole lot about tracking the pid as we clean the temp dir when killing gulp. Just naming the temp dirs something more informative would be a bit nicer. @IgorMinar has more insight into the angular use case, so c.f.-ing him

**Comment by cecchi** [comment]
Somewhat related: Should we consider a different name for the temporary directory itself? I could imagine a case where a project has an existing `tmp` directory. Would renaming to `.broc/` or `.broccoli/` make sense?

**Comment by joliss** [comment]
@cecchi, yes, unless there are unforeseen issues with this, we'll likely use the system `/tmp` dir when available (and it would be configurable as well).

**Comment by stefanpenner** [comment]
* these names seem much more friendly.
* we should work hard to make tmp dir configurable

**Comment by stefanpenner** [comment]
broccoli 1.x has this https://github.com/broccolijs/broccoli/blob/0bc034c5840c3e54e70a2a60153dc71ed41c8afd/lib/builder.js#L272-L292
