### ISSUE TITLE
Separating DAG node and implementation

### ISSUE THREAD

**Issue by joliss** [broccolijs/broccoli#267]
@stefanpenner and @igorminar both brought up the idea of separating the Node class (which represents the DAG structure) from the plugin Implementation. Here's what I came up with, from the perspective of a plugin author.

```js
var Node = require('broccoli-plugin').Node

class TreeMergerNode extends Node {
  constructor(inputNodes, options) {
    this.setInputNodes(inputNodes)
    this.options = options
  }

  getImplementation() {
    return new TreeMergerImplementation(this.getInputPaths(), this.getOutputPath(), this.getCachePath(), this.options)
  }
}

class TreeMergerImplementation { // no base class
  constructor(inputPaths, outputPath, cachePath, options) {
    this.inputPaths = inputPaths
    this.outputPath = outputPath
    this.cachePath = cachePath
    this.options = options
  }

  build() {
    // Build from this.inputPaths into this.outputPath
  }
}

module.exports = TreeMergerNode
```

The idea is, upon initialization, the Broccoli builder will call `getImplementation` once:

```js
var impl = node.getImplementation()
```

and later call `impl.build()` repeatedly.

The whole plugin definition is more wordy, but also more explicit. Maybe it can be improved further. I'm still a bit unhappy with the "Node" and "Implementation" terminology.

Thoughts and insights much appreciated!

**Comment by joliss** [comment]
Base classes like CachingWriter or [DiffingPlugin](https://github.com/angular/angular/blob/d7b9345b6d5f105109991bf3a3a8ee8d310a7a3d/tools/broccoli/diffing-broccoli-plugin.ts) are one open issue: I can't come up with a way to make the inheritance play nicely with the API above.

**Comment by IgorMinar** [comment]
I don't think that there is much value in having custom nodes. I think those can be provided by the core.

This is because all nodes have basically the same interface. They take one or more trees and an options object.

In our current implementation in Angular we generate these nodes automatically be calling `wrapDiffingPlugin(PluginClass)` and exporting the value produced.

This means that for example for tree merger we  can do:

```
class TreeMerger {
  ..
}

export default wrapDiffingPlugin(DiffingTreeMerger);
```

and then use it as:

```
import mergeTrees from '...';

mergeTrees([jsTree, cssTree], {override: true});
```

**Comment by joliss** [comment]
Nodes and implementation are now more easily separatable if desired, since the [`Plugin::getCallbackObject`](https://github.com/broccolijs/broccoli-plugin/blob/master/README.md#pluginprototypegetcallbackobject) method can hand off to another object.

**Comment by stefanpenner** [comment]
:)
