### ISSUE TITLE
transforming less/sass without concat

### ISSUE THREAD

**Issue by tcurdt** [broccolijs/broccoli#272]
Let's say I have

    style1.less
      @import imports/import1.less

    style2.less
      @import imports/import2.less

    imports/
      import1.less
      import2.less

and I would like to transform those files to

    style1.css
    style2.css

yet the `sass` and `less` plugin interfaces seem to take the following parameters:

    inputTrees, inputFile, outputFile, options

**Comment by joliss** [comment]
I hope my comments on IRC helped - if not, let me know and we can reopen.

**Comment by tcurdt** [comment]
Yes, thanks!

So for the record: The usual plugin (less and sass) only supports explicit transforms of single files.
For a more dynamic usage one should better write his/her own plugin.

**Comment by joliss** [comment]
Yup. Maybe check with the authors, they might have an opinion.

Unless it's broccoli-sass, in which case I'm the author and I don't really have an opinion. :D Maybe just fork it to support globs for the input pattern and push it under a new name.
