### ISSUE TITLE
Chainable/sequential builds and/or lifecycle hooks

### ISSUE THREAD

**Issue by meleyal** [broccolijs/broccoli#277]
I'm looking for a way to access the compiled output of one step (the tmp file) in another step.

My goal is to compile C++ with emscripten and require it from transpiled ES6 code, packaged with browserify (don't ask why :)

Here's my main.js file (before babel):

```javascript
// main.js

import * as cpp from './cpp'
console.log(cpp.boo())
console.log(cpp.bla())
```

And my Brocfile:

```javascript
// Brocfile.js

var funnel = require('broccoli-funnel')
var concat = require('broccoli-concat')
var merge = require('broccoli-merge-trees')
var babel = require('broccoli-babel-transpiler')
var emscripten = require('./lib/broccoli-emscripten')
var browserify = require('broccoli-fast-browserify')
var replace = require('replace')

var src = 'src'
var cpp = 'cpp'

var html = funnel(src, {
  files: ['index.html']
})

cpp = emscripten(cpp, {
  inputFiles: ['**/*.cpp'],
  outputFile: './cpp.js',

  callback: function(outputPath) {
    replace({
      match: /\.\/cpp/g,
      replacement: './' + outputPath,
      paths: ['./src/main.js']
    });
  }
})

var js = babel(src)
js = merge([js, cpp])

js = browserify(js, {
  bundles: {
    'web.js': {
      entryPoints: ['**/main.js'],
    }
  },
  browserify: {
    debug: false
  }
})

module.exports = merge([html, js])
```

Obviously browserify is looking for a `cpp.js` file which isn't there as it's in the tmp folder.

My naive idea was to get the tmp file name from a callback in the emscripten step and to replace the import string in `main.js` to point to the temp file. However this doesn't work as the other steps seem to run before the callback.

So my question is: is there a way to chain the steps together to run sequentially or be notified when one step is complete before handing off to the next step?

Or is there an easier way to achieve this with Broccoli?
If not consider this a feature request #271 :-)

Thanks!

**Comment by joliss** [comment]
> I'm looking for a way to access the compiled output of one step (the tmp file) in another step.

Chaining build steps like this is exactly what Broccoli is made for. Your Brocfile looks perfectly reasonable for doing this.

> Obviously browserify is looking for a cpp.js file which isn't there as it's in the tmp folder.

I'm not sure what's going on - I'd expect it to look in the tmp folder that belongs to the `js` tree you're passing in. You'll have to debug this. I'd suggest wrapping the tree in `instrument.print` from [broccoli-debug](https://github.com/joliss/broccoli-debug) or taking a look at the broccoli-fast-browserify source code.

**Comment by meleyal** [comment]
Thanks, I'll give broccoli-debug a try. The docs say you can inspect the tree with `ls`, does this mean via the shell?

**Comment by joliss** [comment]
Yup.

**Comment by meleyal** [comment]
Thanks I got this working, I just hadn't understood how broccoli tree transformations work.
