### ISSUE TITLE
Question: Can broccoli run in es6

### ISSUE THREAD

**Issue by j-walker23** [broccolijs/broccoli#280]
Hi all, new to broccoli. Super cool so far, literally building my sass 10 seconds faster!
So thank you!

Quick question. Does broccoli have an option to run the brocfile in es6, like gulps gulp.babel.js?

I know I can have a regular es5 file require babel, and then other files can be in es6. Just curious if it was already possible to cut out that extra step.

**Comment by stefanpenner** [comment]
Not currently

**Comment by joliss** [comment]
I think it's best to wait for Node to pick up new ES6 features, rather than trying to add support to Broccoli. The latest Node version 4.1.2 supports quite a few already, such as classes and arrow functions.

**Comment by j-walker23** [comment]
Thanks for the response
