### ISSUE TITLE
Error: ENOENT: No such file or directory, stat 'C:\...'

### ISSUE THREAD

**Issue by cbornhoft** [broccolijs/broccoli#288]
This is an issue that popped up completely at random, and I haven't been able to figure out. This is running within an ember-cli project (test-ember) on Windows 7 x64 using the latest node (5.2.0) and npm (3.5.2) available. Tried with older versions as well.

With `test-ember/tmp` empty initially, the first build is always successful:

    Build successful - 4906ms.
    
    Slowest Trees                                 | Total
    ----------------------------------------------+---------------------
    ConcatWithMaps: Concat: Vendor                | 1724ms
    SassCompiler                                  | 404ms
    
    Slowest Trees (cumulative)                    | Total (avg)
    ----------------------------------------------+---------------------
    ConcatWithMaps: Concat: Vendor (1)            | 1724ms
    Babel (13)                                    | 623ms (47 ms)
    SassCompiler (1)                              | 404ms

However, upon any file change, after the `/tmp` directory is filled, the following error appears:

    file changed templates\articles\index.hbs
    ENOENT: no such file or directory, stat 'C:\test-ember\tmp\broccoli_merge_trees-output_path-20taVGO5.tmp\modules\ember-cli-app-version\templates'
    Error: ENOENT: no such file or directory, stat 'C:\test-ember\tmp\broccoli_merge_trees-output_path-20taVGO5.tmp\modules\ember-cli-app-version\templates'
        at Error (native)
        at Object.fs.statSync (fs.js:893:18)
        at Object.realpathSync (fs.js:1540:12)
        at symlinkWindows (C:\test-ember\node_modules\ember-cli\node_modules\symlink-or-copy\index.js:87:26)
        at symlinkOrCopySync (C:\test-ember\node_modules\ember-cli\node_modules\symlink-or-copy\index.js:56:5)
        at Babel.Filter._handleFile (C:\test-ember\node_modules\ember-cli\node_modules\broccoli-babel-transpiler\node_modules\broccoli-persistent-filter\index.js:101:12)
        at Babel.<anonymous> (C:\test-ember\node_modules\ember-cli\node_modules\broccoli-babel-transpiler\node_modules\broccoli-persistent-filter\index.js:88:21)
        at C:\test-ember\node_modules\ember-cli\node_modules\promise-map-series\index.js:11:14
        at lib$rsvp$$internal$$tryCatch (C:\test-ember\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:493:16)
        at lib$rsvp$$internal$$invokeCallback (C:\test-ember\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:505:17)

Any subsequent file changes produce the same error. I've tried updating [`broccoli-persistent-filter`](https://github.com/stefanpenner/broccoli-persistent-filter) to the latest (1.1.6) according to @stefanpenner 's suggestion on [this ember-cli issue](https://github.com/ember-cli/ember-cli/issues/4782#issuecomment-152016883), however in my case, no files were deleted, and the error initially appeared on a file change.

**Comment by stefanpenner** [comment]
I suspect you have an old/buggy version of some add-on, maybe share your

```
npm ls
```

**Comment by cbornhoft** [comment]
Without `--depth=0`, it's over 2K lines. Let me know if you need the full list.

    PS C:\test-ember> npm ls --depth=0
    test-ember@0.0.1 C:\test-ember
    ├── active-model-adapter@2.0.1
    ├── bourbon@4.2.6
    ├── broccoli-asset-rev@2.2.0
    ├── ember-cli@1.13.13
    ├── ember-cli-app-version@0.5.0
    ├── ember-cli-babel@5.1.6
    ├── ember-cli-content-security-policy@0.4.0
    ├── ember-cli-dependency-checker@1.1.0
    ├── ember-cli-htmlbars@0.7.9
    ├── ember-cli-htmlbars-inline-precompile@0.2.0
    ├── ember-cli-ic-ajax@0.2.1
    ├── ember-cli-inject-live-reload@1.3.1
    ├── ember-cli-qunit@1.1.0
    ├── ember-cli-release@0.2.3
    ├── ember-cli-sass@5.2.0
    ├── ember-cli-sri@1.1.0
    ├── ember-cli-susy@1.0.0
    ├── ember-cli-uglify@1.2.0
    ├── ember-data@2.2.1
    ├── ember-disable-proxy-controllers@1.0.1
    ├── ember-export-application-global@1.0.4
    ├── ember-power-select@0.6.5
    ├── normalize-scss@4.0.3
    └── npm@3.5.2 extraneous

**Comment by stefanpenner** [comment]
the following is outdated (and had issues with path stability, the recent performance improvements require):

> ├── ember-cli-htmlbars@0.7.9

we are now at 1.0.1, give updating a try.

The symptom you described would indicate this is likely to be the offender as it described a missing template after incremental `ENOENT: no such file or directory, stat 'C:\test-ember\tmp\broccoli_merge_trees-output_path-20taVGO5.tmp\modules\ember-cli-app-version\templates'` And earlier version of many broccoli-plugins had path stability issues (that impeded performance).

**Comment by cbornhoft** [comment]
Hmm, you would be correct, as always, Stefan!

Any reason `package.json` had this set to that specific version? I have to change the line from `0.7.9` to `^1.0.0` in order for it to finally update. Assuming `ember-cli` set that itself.

**Comment by stefanpenner** [comment]
> Any reason package.json had this set to that specific version? I had to manually change the line from 0.7.9 to ^1.0.0 in order for it to finally update. Assuming ember-cli set that itself.

Likely it was generated by an old version of ember-cli. The recent versions will blueprint `^1.0.1` https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/files/package.json#L29

**Comment by stefanpenner** [comment]
> Hmm, you would be correct, as always, Stefan!

I'll assume this means the issue is resolved, if not let me know in detail whats still wrong and I can reopen + investigate.
