### ISSUE TITLE
Error conventions

### ISSUE THREAD

**Issue by stefanpenner** [broccolijs/broccoli#290]
We currently have some error conventions, for example `error.filename`, `err.col` and  `error.line`.

I believe we all agree this is quite useful, but leaves much to be desired. For example:
1. It is possible to have multiple files that together caused a failure (typescript compiler for example can report failures across multiple files)
2. we would like both terminal friendly, and browser friendly syntax highlighted contextual error messages..

Maybe more?

**Comment by khomyakov42** [comment]
+1. I would like to be able to output a piece of code in which the error occurred

**Comment by stefanpenner** [comment]
We have done a good job I think in ember-cli of combining all the pieces to output useful and good error messages. As part of upgrading ember-cli, I hope to forward port any learnings to this project.
