### ISSUE TITLE
Brocfile.js doesn't reload on change.

### ISSUE THREAD

**Issue by CaseyLeask** [broccolijs/broccoli#294]
If you write

``` js
module.exports = 'public'
```

and run `broccoli serve`, then change `Brocfile.js` to

``` js
module.exports = 'src'
```

Broccoli continues to check 'public' for changes, not 'src'.
Is it possible for Broccoli to keep track of when `Brockfile.js` changes?

**Comment by stefanpenner** [comment]
likely 1.0 which will move the tmp dir out of the root of the project.

**Comment by joliss** [comment]
Actually, changes to `Brocfile.js` still aren't monitored, and likely won't ever be (unless you somehow manually watch them), per my comment here: https://github.com/broccolijs/broccoli/issues/34#issuecomment-35886022

**Comment by stefanpenner** [comment]
But in 1x it will be more plausible to implement without killing perf

**Comment by joliss** [comment]
Ah, yes.
