### ISSUE TITLE
Is it possible to run the server using SSL?

### ISSUE THREAD

**Issue by courthead** [broccolijs/broccoli#295]
I usually use SSL in local development (https://localhost), but I'm not sure how to get `broccoli serve` to use SSL, and I can't find any tips online. Is this possible?

**Comment by jakedetels** [comment]
Pretty sure that's not possible today with Broccoli.  This would be helpful for my team as well.

**Comment by stefanpenner** [comment]
Hid you use ember-cli, which can run any brocfile, you do have this option

**Comment by courthead** [comment]
@stefanpenner Works like a charm, thanks!
