### ISSUE TITLE
broccoliplugins.com domain expired

### ISSUE THREAD

**Issue by Jarred-Sumner** [broccolijs/broccoli#298]
The domain `broccoliplugins.com` is linked to in the README under the Plugins section. When you go to it, it shows this page:

![image](https://cloud.githubusercontent.com/assets/709451/14397850/c5693798-fd94-11e5-8cff-a5926b02ecd5.png)

Is that website under a different domain now? Would a PR that removes the link to this domain in the README be welcome (or, alternatively, one that updates the domain to the proper one if it exists)?

**Comment by stefanpenner** [comment]
oh oh, this was just a mistake...

**Comment by rixo** [comment]
You should remove the link from the README right away because, meanwhile, confused users click one or two of these links and the squatter is getting rewarded money for having stolen your domain...

**Comment by stefanpenner** [comment]
Cc @joliss

**Comment by Jarred-Sumner** [comment]
Another issue is that it makes the project look inactive, which is bad when a new user sees it.
