### ISSUE TITLE
How to build repeatedly without serving?

### ISSUE THREAD

**Issue by BryanCrotaz** [broccolijs/broccoli#300]
I'm building backend files to be deployed to AWS Lambda. So there's nothing for a local web server to serve up. 

I can't see how to configure build to build and watch for changes (serve must be doing this I assume). Is this possible or easy to add?

**Comment by qm3ster** [comment]
https://www.npmjs.com/package/broccoli-clext
I haven't tried it myself, but might.
Includes rimraf for output (behind `--clean`) and a watch for directory build.
If you try it please report whether it builds incrementally like `serve` or just runs `build` any time anything changes.

**Comment by stefanpenner** [comment]
tracking this here: https://github.com/broccolijs/broccoli/issues/331
