### ISSUE TITLE
Move multidep into regular dependencies?

### ISSUE THREAD

**Issue by davewasmer** [broccolijs/broccoli#302]
Trying to use broccoli as a dependency seems to require `multidep` to be installed (because of the post-install hook script), but it's marked as a devDep rather than a regular dep. This seems to result in the install failing unless multidep is installed separately. I assume moving `multidep` into the regular dependencies would fix this?

**Comment by rwjblue** [comment]
I believe this is a testing only dependency, so `postInstall` doesn't seem appropriate here.  We could move to `prepublish` (which also seems slightly annoying) so that it is only ran when calling `npm install` (without arguments) of this library (not in consuming apps)...

**Comment by wayne-o** [comment]
What's the solution here? It's stopping me from upgrading and making use of  ```builder.outputPath``` - is there a quick fix I an use to overcome this?

**Comment by davewasmer** [comment]
@wayne-o one workaround is to install multidep globally (`npm i -g multidep`)

**Comment by cebor** [comment]
please remove the `postinstall` 👍

**Comment by joliss** [comment]
Thanks -- I somehow hadn't realized that `postinstall` also runs when Broccoli is pulled in as a dependency, and not just after a local "npm install". I've released a fixed v1.0.0-beta.7.
