### ISSUE TITLE
`serve` or `build` detection

### ISSUE THREAD

**Issue by qm3ster** [broccolijs/broccoli#304]
How can I see inside my _Brocfile.js_ environment whether `broccoli` was invoked with `serve` or `build`?
I want to conditionally bypass BrowserSync.

**Comment by stfsy** [comment]
You could use node's process object

```javascript
const tasks = {
    build: 'build',
    serve: 'serve'
}

const building = process.argv.indexOf(tasks.build) > 0
const serving = process.argv.indexOf(tasks.serve) > 0
```
