### ISSUE TITLE
Navigating the plugin ecosystem?

### ISSUE THREAD

**Issue by kylecordes** [broccolijs/broccoli#305]
The issue tracker is probably not the right place for this; but I did not see any links to any other place for general non-issue discussion, so I will put this here and hopefully someone will point out I missed a link somewhere.

What I wonder is: is there in a good way at the moment to navigate the broccoli plug-in ecosystem? I find myself wanting a typescript plug-in. By following the provided link to an unsorted (?), paged list of plug-ins:

https://www.npmjs.com/browse/keyword/broccoli-plugin

... then clicking through each page and searching for typescript, then searching the web also, it appears there are currently at least five candidate broccoli typescript plug-ins:
- https://www.npmjs.com/package/broccoli-typescript-compiler
- https://www.npmjs.com/package/broccoli-typescript
- https://www.npmjs.com/package/broccoli-tsc
- https://www.npmjs.com/package/broccoli-typescript-incremental
- https://github.com/angular/angular-cli/blob/master/lib/broccoli/broccoli-typescript.js (inside the nascent angular-cli tool)

Unfortunately, with a few minutes of browsing it is not clear whether any of these are actually suitable for use with the reasonably current typescript, working error reporting and configurability, etc.  They seem to vary in age since last activity, from a few months to a couple of years. At least two of them mention another one's abandon-ness as a reason to exist.

This makes me wonder: Am I overlooking a good way to navigate the plug-in ecosystem? Is it really this tough to find a current, working, maintained plug-in for any particular need? Did I just get unlucky and choose a particular need with the situation is messy?

**Comment by stefanpenner** [comment]
https://www.npmjs.com/browse/keyword/broccoli-plugin is currently the best place, in the past we had a plugin site, and we may once-again create one (As time permits).

Readme has been updated to point to ^
