### ISSUE TITLE
Extracting broccoli modules

### ISSUE THREAD

**Issue by stefanpenner** [broccolijs/broccoli#309]
First one we have extracted is:
- https://github.com/ember-cli/broccoli-brocfile-loader

We plan to extract
- builder
- middleware
- maybe more

@joliss would you like these moved to the broccolijs org?

**Comment by joliss** [comment]
Related: https://github.com/ember-cli/ember-cli/pull/6208

As I said in my comment there, let's finish up 1.0 and then split things.

And yes to moving things to the broccolijs org.

**Comment by stefanpenner** [comment]
@joliss https://github.com/ember-cli/ember-cli/pull/6208#issuecomment-245048638
