### ISSUE TITLE
build in-place

### ISSUE THREAD

**Issue by cekvenich** [broccolijs/broccoli#314]
I have large projects w/ media files served 'statically' - and I need to build in same directory as file.

For any .sass found in folder, just make a css.
For any .pug, make html. 

I have written this in pure .js, but I'd like to do it in broccoli. broccoli serve appears not to build, and broccoli build want's to make a new directory away from my http server. 

Can input tree and output tree be same?
Should I write own script: const builder = new broccoli.Builder(DIR)

How?
Is it possible?

(Later I have to write my own filters since  I do complex pug things with other pre-processors built in).

**Comment by stefanpenner** [comment]
> Can input tree and output tree be same?

If one uses the builder independently of the watcher, and the plugins being used only read the files (which are not the output), it could be made to work.

**Comment by cekvenich** [comment]
I'm new to broccoli. Right now it want's to write to a different folder each time and serve appears not to even write. (I can show example of how it works in .js for me now if that helps.)

Yes, they are different files, ex: read Sass, write css in same folder. 

How would I do that please?

**Comment by joliss** [comment]
I'm not sure I have a good answer for your question, but in general I'd like to work on improving Broccoli's documentation so it's easier to get started.
