### ISSUE TITLE
List changed files in 1.x via Watcher

### ISSUE THREAD

**Issue by ghempton** [broccolijs/broccoli#317]
Exploring upgrading to Broccoli 1.x. I see that `broccoli-sane-watcher` has been deprecated. Is there a way to get access to a list of changed files inside the `buildSuccess` event similar to what was available in sane watcher? The use case is triggering live reloads based on changed files.

**Comment by joliss** [comment]
broccoli-sane-watcher is simply part of the core broccoli package now, for what it's worth.

As for your question, there's no way to get a list of changed source files right now. Your use case seems a bit too narrow to add this.

**Comment by ghempton** [comment]
broccoli-sane-watcher used to include the changed files as part of the event that was emitted: https://github.com/broccolijs/broccoli-sane-watcher/blob/master/index.js#L122

This seems like a crucial piece of functionality for any development server. Last I checked, ember-cli depended on this as well.

**Comment by rwjblue** [comment]
Confirm, ember-cli does use the list of changed files (both for reporting/instrumentation and for some of our API's like live reload filtering).

**Comment by ghempton** [comment]
@joliss can we reopen this issue?

@rwjblue is upgrading broccoli something that will ever be in ember-cli's future?

**Comment by rwjblue** [comment]
Yes, unifying back onto broccoli@latest is definitely on our roadmap.
