### ISSUE TITLE
Broccoli development plan

### ISSUE THREAD

**Issue by chrmod** [broccolijs/broccoli#320]
is broccoli still in development and if so, what is its development plan?

ember-cli broccoli fork diverges and so do addons that rely on ember-cli changes: 
https://github.com/rwjblue/broccoli-slow-trees/issues/9

The situation is similar to incompatibilities introduced by 1.x release. Outside of ember land there are still projects relaying on pre 1.x as they depend on addons that have not been upgraded to new APIs.

Since Broccoli 1.x has landed we should work towards merging the forks and unifying addons ecosystem. 

Otherwise we will need some kind of compatibility table for every addon if we want to know if it works with 0.x, 1.x, ember-cli/broccoli..

**Comment by mtimofiiv** [comment]
I agree with @chrmod, I'm actually not able to use Broccoli's current version at all since so many plugins do not currently work for it and it seems there is not really a drive to update them.

**Comment by stefanpenner** [comment]
> is broccoli still in development and if so, what is its development plan?

I believe our first order of business is to unify the ember-cli fork and 1.0 of broccoli, following this we have plans to re-work various marketing and teaching material.

Unfortunately, broccoli itself was iterating at a rate that was to slow for those of us working on ember-cli, we had to make the tactical choice to make a friendly fork. It's a bummer those forks needed to exist in the first place.

Our broad-stroke plans this summer are to:

* get rid of the ember-cli/broccoli fork, by backport/forward port the various fixes required to transition to 1.0
* fix popular plugins that then still need to be fixed to work with 1.0
* work on improved marketing material and tutorials.

These efforts (although ad-hoc) have been taken place, but we need to drive them to completion at a faster clip.

**Comment by stefanpenner** [comment]
I have been and plan to give broccoli some TLC this week. Specifically the goal is to tidy-up, fix outstanding blockers preventing the ember-cli upgrade. I aim to also exist this week with some actionable next steps.

**Comment by stefanpenner** [comment]
I've created an issue for "shit thats broken on 1.x" https://github.com/broccolijs/broccoli/issues/332 Please feel to pile on.
