### ISSUE TITLE
trying to run gitbook serve but it's showing me this error Error: ENOENT: no such file or directory, stat '/home/christy/.config/Postman/SS' how do i rectify it

### ISSUE THREAD

**Issue by chris4real** [broccolijs/broccoli#356]
trying to run gitbook serve but it's showing me this error
Error: ENOENT: no such file or directory, stat '/home/christy/.config/Postman/SS'
how do i rectify it

**Comment by stefanpenner** [comment]
this seems to have gone stale, will gladly reopen if a reproduction can be provided.
