### ISSUE TITLE
readme should also describe programmatic builder usage

### ISSUE THREAD

**Issue by stefanpenner** [broccolijs/broccoli#368]
something like: https://github.com/broccolijs/broccoli/blob/master/lib/builder.js#L29-L40

**Comment by cafreeman** [comment]
I'd like to take a stab at this in the next few days

**Comment by cafreeman** [comment]
@stefanpenner just to close the loop, I opened a PR for this [here](https://github.com/broccolijs/broccoli/pull/369).

**Comment by stefanpenner** [comment]
@cafreeman ah fantastic, looks great!
