### ISSUE TITLE
Broccoli build returns 0 on build failure

### ISSUE THREAD

**Issue by conartist6** [broccolijs/broccoli#388]
When plugins fail throwing errors, `broccoli build` still returns exit code 0, despite the fact that it has not built successfully, and has not created the build target directory.

**Comment by peabnuts123** [comment]
Uhhhh … just found this issue myself. How does … broccoli work with this behaviour … ? You can't use it in a build pipeline at all. Unless I'm missing something?

**Comment by rwjblue** [comment]
Hmmm, this is quite surprising. Does someone have time to make a small reproduction?

**Comment by conartist6** [comment]
@rwjblue Are you saying that sometimes build errors in plugin code are caught and cause non-zero exits? At the most basic plugin API level, are plugins meant to catch their own errors?

I don't know how much help I can be. It's been a whole year and I don't even remember what I was trying to do when I encountered this. Hazards of leaving bugs sit for ages.

**Comment by stefanpenner** [comment]
fix https://github.com/broccolijs/broccoli/pull/456

**Comment by stefanpenner** [comment]
fixed with v3.5.1 🎉 release thanks to @chiragpat
