### ISSUE TITLE
Ember Memoization issue

### ISSUE THREAD

**Issue by lifeart** [broccolijs/broccoli#404]
reproduction https://github.com/lifeart/ember-broccoli-memo-debug
how?
`yarn; ember s`
change `application.hbs` -> no app refresh, only silent rebuild. After f5 - no changes.

![image](https://user-images.githubusercontent.com/1360552/58050618-84fca880-7b58-11e9-9969-a80abfa72d04.png)

ref to: https://github.com/broccolijs/broccoli/pull/396

**Comment by rwjblue** [comment]
I'm not sure that we expect the new memoization functionality to work with currently released ember-cli versions? Specifically, the changes landed in #396 require changes in ember-cli for it to function properly (see https://github.com/ember-cli/ember-cli/pull/8614).

**Comment by lifeart** [comment]
Upsa, was thinking it should go out if the box.

with

**Comment by oligriffiths** [comment]
@lifeart this isn't fully implemented in Ember-CLI yet, please hold off on testing anything until we release a specific build with this support

**Comment by stefanpenner** [comment]
We will land part 2 in the next few days.

**Comment by stefanpenner** [comment]
Should be fixed now
