### ISSUE TITLE
Broccoli Next Steps

### ISSUE THREAD

**Issue by stefanpenner** [broccolijs/broccoli#414]
Notes from our meeting:

- [x] unify ember-cli / broccoli server
- [ ] unify live-reload
- [x] plugin `this.input` using something like https://github.com/SparshithNR/fs-merger
- [x] plugin `this.output` facade (and wired up to memoization)
- [ ] enable colored syntax highlighting in error messages from babel (turn babel's highlighting back on, and support ansi  -> html/css for our error page)
- [x] typescript support
- [x] improved debugging / logging

- [ ] deprecate inputPaths[x] + outputPath

**Comment by thoov** [comment]
typescript support

**Comment by astronomersiva** [comment]
Created a [PR](https://github.com/broccolijs/broccoli/pull/415) to address the colored syntax highlighting of Babel error messages.
