### ISSUE TITLE
Complains that port is in use when running multiple processes on multiple ports

### ISSUE THREAD

**Issue by danmcclain** [broccolijs/broccoli#55]
I have a broccoli (`broccoli serve`) on port 4200. If I try running a second instance with `broccoli server -p 4700`, it works like it should, starting a second instance and binding to port 4700, but it has the following output

```
╰─$ broccoli serve --port 4700                                                                  1 ↵
Serving on http://0.0.0.0:4700


... Uhoh. Got error listen EADDRINUSE ...
Error: listen EADDRINUSE
    at errnoException (net.js:901:11)
    at Server._listen2 (net.js:1039:14)
    at listen (net.js:1061:10)
    at Server.listen (net.js:1127:5)
    at Server.listen (/Users/dan/Projects/highways/frontend/node_modules/broccoli/node_modules/tiny-l
r/lib/server.js:138:15)
```

(Stacktrace truncated)

As soon as I stop the instance on 4200, starting the instance on 4700 works without errors. My guess is that it always checks port 4200, regardless of the port option passed in. If I wasn't on the train, I would dig into the code :smile:

**Comment by stefanpenner** [comment]
This is no longer an issue with this lib
