### ISSUE TITLE
Build should always return a promise

### ISSUE THREAD

**Issue by MajorBreakfast** [broccolijs/broccoli#64]
https://github.com/joliss/broccoli/blob/master/lib/builder.js#L15

If a build is scheduled, then the promise for the scheduled build should be returned. This would make it safe to call `.then()` on the output.

Also: If a build is currently in progress, it could schedule another build that runs after the current one has finished and `build()` returns the promise for that build then.

**Comment by stefanpenner** [comment]
this has been fixed
