### ISSUE TITLE
Expose Watcher and middleware?

### ISSUE THREAD

**Issue by moudy** [broccolijs/broccoli#69]
I want to use broccoli as middleware instead of running `broccoli serve`. This isn't currently possible but I hacked to together an example by requiring the Watcher and middleware directly.

```
var broccoli = require('broccoli');
var Watcher =  require('./node_modules/broccoli/lib/watcher');
var middleware =  require('./node_modules/broccoli/lib/middleware');

var app = require('express')();

var tree = broccoli.loadBrocfile();
var builder = new broccoli.Builder(tree);
var watcher = new Watcher(builder);
var assets = middleware(watcher);

if ('development' === app.get('env')) {
  app.use(assets);
}

app.listen(3000);
// if Brocfile.js had configuration to serve app.js 
// http://localhost:3000/app.js would be served
```

From https://github.com/joliss/broccoli/issues/7 it seems like you are considering adding this in future. If this feature is built in then there's no need for exposing `Watcher` and `middleware` but if should exist as a module then they would need to be exposed.

Any thoughts? Thanks for the great work on this project.

**Comment by cmmartin** [comment]
Did this ever happen? After poking around it seems I can probably accomplish this with [broccoli-timepiece](https://github.com/rwjblue/broccoli-timepiece) and a few lines of custom code, but I'm curious if there is a standard solution to the problem of being unable to communicate with a local server (thanks to CORS restrictions across ports) while running ```broccoli serve```. Basically I want to broccoli serve from an express route

**Comment by joliss** [comment]
I just pushed 0.16.7, which exports everything: https://github.com/broccolijs/broccoli/blob/master/lib/index.js

You should be able to use `getMiddleware(new Watcher(builder))` to get a middleware for your express server.

**Comment by joliss** [comment]
More to your question: I'm not sure that there's a canonical solution for the CORS problem. There's some discussion in #208, but it didn't really go anywhere. My sense is that you'd generally run your own express server that uses Broccoli as a middleware and also serves/proxies the API.

**Comment by cmmartin** [comment]
Thanks. I ended up doing exactly that. I got the middleware running with a single line of js and using the same Express app as an API proxy solves the CORS issue. This is a better solution than broccoli setting a CORS header in my opinion
