### ISSUE TITLE
Refactor Watcher to not poll?

### ISSUE THREAD

**Issue by ericf** [broccolijs/broccoli#72]
I've been noticing that the Broccoli Watcher task is taking up a constant 4% CPU on a medium-sized project. I think Watcher should _not_ poll by default, but instead preform a check every time its `then()` method is called.

If someone wants the Watcher to poll, then they could easily setup a `setInterval(watcher.check, 100)`. This would also ensure that when the middleware/server receives a request for a file, it will always be built and up to date.

@joliss Thoughts? If this seems good to you, I'd be happy to issue a PR for this change.

**Comment by stefanpenner** [comment]
after long wait, broccoli ships with broccoli-sane-watcher by default. (WHich defaults to a non polling watcher).
