### ISSUE TITLE
Watcher too aggressive, triggers LiveReload for editor tmp/swap files

### ISSUE THREAD

**Issue by bcardarella** [broccolijs/broccoli#94]
_[Original title: "Live Reload too aggressive" - JL]_

See: https://github.com/stefanpenner/ember-cli/issues/291

It was speculated that this can be addressed in Broccoli. The issue is the live reload server is reloading on tmp files, swap files, etc... file system events that occur simply because I open a file in vim should not kick off the reload.

**Comment by scottsword** [comment]
@joliss Where has the LiveReload functionality been moved to?

**Comment by joliss** [comment]
Tools like Ember CLI bring their own LiveReload functionality at the moment. There's no LR support in Broccoli core (see https://github.com/broccolijs/broccoli/issues/256). Maybe we'll make it easier to add pluggable LiveReload support in the future.

**Comment by stefanpenner** [comment]
if there are common files, feel free to add them to https://github.com/krisselden/broccoli-sane-watcher/blob/master/index.js#L9-L11 and they will be ignored from the builder side of things.

**Comment by stefanpenner** [comment]
Now that broccoli owns both:

* the watcher
* the tmpdir

We can totally do this.

Details would likely be:
* ensure the watcher is aware of `tmpdir` https://github.com/broccolijs/broccoli/blob/eef69e2879688fa99d02b2b152f23b8b9b7852a4/lib/builder.js#L48
* have the watcher warn when you try to watch such directories.
* have the watcher not watch directories contained within the above mentioned `tmpdir`

**Comment by stefanpenner** [comment]
It's also worth pointing out 1.0 doesn't have this issue (as configured by default) as the tmp dir is located outside of the project root.

**Comment by stefanpenner** [comment]
Now with 2.0, we have moved the default `tmp` to system tmp, this can now be closed :)
