### ISSUE TITLE
LiveReload not working

### ISSUE THREAD

**Issue by IderAghbal** [broccolijs/broccoli#98]
I followed the steps discribed in [this tweet](https://twitter.com/jo_liss/status/435469369456345088/photo/1)  but I got the message
`Could not connect to LiveReload server. Please make sure that a compatible LiveReload server is running.` when clicking on the extension's icon
why?

**Comment by alekspetrov** [comment]
Get into this issue. LiveReload not working. 

node 0.12.5
npm  2.11.2
broccoli-cli 1.0.0
broccoli 0.16.3

Serving with broccoli serve on default port and localhost (http://localhost:4200). 
Clicking on LR icon says: Could not connect to LiveReload server. Please make sure that LiveReload 2.3 (or later) or another compatible server is running. 

Reinstalling broccoli-cli has no effect. 

Whats interesting, my ember apps are reloading normally, and Gulp also reload page correctly. I didn't ever use broccoli for non ember projects, maybe I do not understand something?

**Comment by alekspetrov** [comment]
As I can see in #256, Livereload removed from broccoli core ((( And the funniest thing there is no alternative. Ok, turning back to gulp.
